### ISSUE TITLE
No units - change params?

### ISSUE THREAD

**Issue by ganupuru** [Julie-Fabre/bombcell#178]
Hello Julie,
I'm trying to use bombcell to curate a Neuropixels dataset sorted with Kilosort 4. I have 587 clusters in this set, and looking at them in Phy2, I can pretty confidently see that there is real neural activity there, whether or not they're good units.

However, bombcell is not picking up anything (no good units or MUA), and as you know, it recommends changing parameters. Unfortunately, I'm not savvy enough to know where to start. Are there any obvious ones to tweak first, or specific metrics that might indicate?

Preetham

**Comment by Julie-Fabre** [comment]
Hi Preetham, 

Thanks for your message!

It does sound like you'll need to tweak some parameters. I'm curious about why things are so different for you. Could you tell me which brain regions you're recording from, in which animal model, and in which setting (headfixed acute, headfixed chronic, freely-moving, ...). 

Could you send me the output figures (just a screen shot is fine) of bombcell? The plots that look something like this (below)
![image](https://github.com/user-attachments/assets/9952c4c0-34d7-4e7e-a4f8-d4a414ca300b)
![image](https://github.com/user-attachments/assets/a8867e5c-dd13-4768-9cc7-52365ac53c44)
![image](https://github.com/user-attachments/assets/a52f5669-f669-44e9-90d0-df9597622b33)
![image](https://github.com/user-attachments/assets/7eafb798-346a-49eb-9c32-f4fa7042e4aa)
![image](https://github.com/user-attachments/assets/d1661625-d5e0-4822-a8e2-dca43ce699cf)

**Comment by ganupuru** [comment]
Thanks for the quick reply.  I'm recording from rat prefrontal cortex, chronic/freely moving. Here are my outputs:

![bombcell_output](https://github.com/user-attachments/assets/ef5d97e3-4dd9-4380-bc06-452e7480246e)

**Comment by Julie-Fabre** [comment]
Hi Preetham, 

Thank you for the information and the plots! 
Are you sure this is the correct waveform plot? There are very few waveforms plotted despite many neurons in the UpSet plots (the blue histograms).

**Comment by ganupuru** [comment]
Yes, that's the one that's displayed along with those other plots. 

Could this be an issue with how I'm loading the data? If it makes any difference, I'm defining ephysRawFile as the continuous.dat file that outputs from open ephys (the file itself, not the directory). I'm defining ephysMetaDir as a structure (not a character array) where my oebin file is. I'm defining the ephysKilosortPath as the "kilosort4" subdirectory.

**Comment by Julie-Fabre** [comment]
Sorry I think I got confused by your top MUA upset plot (which suggested you had more than 400 MUA units)- I guess the bottom one is the correct one? :)

In that case, the proportions don't look so off to me - 2/18 (>10 % are good single units - we usually expect this number to be ballpark around between 10 to 25 %) . That being said, looking at the histograms, there are some value you can tweak but I'm not sure the histograms are the ones for your dataset though. I can see you have a slightly older version of bombcell too (from the plots). Would you be able to download the latest version of bombcell are re-run it on your dataset and then add the output histogram again? Thanks a lot! 

![image](https://github.com/user-attachments/assets/30e0b35a-0840-4b54-90b0-e7f4aca0c916)

**Comment by ganupuru** [comment]
OK, reinstalling bombcell completely fresh, I'm now getting the following error in MATLAB at line 130 of extractRawWaveformsFast: Unable to perform assignment because the size of the left side is 1-by-61-by-383 and the size of the right side is 383-by-61.

Which seems like a pretty minor error, but it looks like one of those variables is formatted incorrectly. Is this error immediately familiar to you, or should I work backwards through the code and figure it out? Sorry, I know this is outside the original issue.

**Comment by Julie-Fabre** [comment]
No need to apologize, thank you for bringing that up! A small bug had crept in (sorry about that!). Could you pull again? Things should be fixed now :)

**Comment by ganupuru** [comment]
OK, I think we're good now. I'm getting sensible results after updating. Thanks for all the help.

**Comment by Julie-Fabre** [comment]
Great! Let me know if you run into any other issues or questions :)
