### ISSUE TITLE
Unable to plot distance metrics 

### ISSUE THREAD

**Issue by jennablain** [Julie-Fabre/bombcell#208]
In this function:
unitQualityGuiHandle = bc.viz.unitQualityGUI(memMapData, ephysData, qMetric, forGUI, rawWaveforms, ...
    param, probeLocation, unitType, loadRawTraces);
I want to include the distance metrics in my plot, but receieve this error

Unrecognized field name "Xplot".

Error in bc.viz.unitQualityGUI>updateUnit (line 608)
    set(guiData.currIsoD, 'XData', forGUI.Xplot{iCluster}(:, 1), 'YData', forGUI.Xplot{iCluster}(:, 2))

**Comment by Julie-Fabre** [comment]
Hi Jenna, 

Thanks for your message! We've currently temporarily disabled that plot - it wasn't very informative. We're working on adding more useful plots here - it'll be ready soon and I'll comment on this issue when it is :)

**Comment by Julie-Fabre** [comment]
Closing this for now - we now have plans to completely refactor the GUI. This will take a while - we have it on the [roadmap](https://github.com/Julie-Fabre/bombcell/wiki/Roadmap) for end of next year. 
For now, if you want good visualizations of distance metrics you can use the "FeatureView" in [phy](https://phy.readthedocs.io/en/latest/)
