### ISSUE TITLE
Warning: could not plot global plots 

### ISSUE THREAD

**Issue by jennablain** [Julie-Fabre/bombcell#215]

**Comment by Julie-Fabre** [comment]
Hi again, thanks for your message! Are you still having issues with this or should close this? :)

**Comment by jennablain** [comment]
You can close this! The reason it wasn’t plotting is because I have no good units (the more recent inquiry).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Julie-Fabre** [comment]
Gotcha - that is still odd behavior but I'll stick to the other github issue because they're related. Thanks!
