### ISSUE TITLE
No good units detected: which parameters to modify

### ISSUE THREAD

**Issue by jennablain** [Julie-Fabre/bombcell#216]
Even though I know I have some good units in my recording, it is not detecting any single units. Which parameters should I modify first?

**Comment by jennablain** [comment]
<img width="529" alt="Screenshot 2024-11-21 at 1 11 39 PM" src="https://github.com/user-attachments/assets/4b952f93-9e2b-48e3-9985-71f6ec44e69e">
<img width="880" alt="Screenshot 2024-11-21 at 1 11 46 PM" src="https://github.com/user-attachments/assets/ba6b187e-8d5b-4a44-bf04-cb41ea26c976">
<img width="796" alt="Screenshot 2024-11-21 at 1 12 06 PM" src="https://github.com/user-attachments/assets/1e074c07-1ef9-416c-944f-ca0a3c097a71">

**Comment by jennablain** [comment]
These are the results I obtain from one recording. We are recording from the IC. There seems to be specific parameters that are causing this separation, but I was not sure of reasonable values.

**Comment by Julie-Fabre** [comment]
Hi Jenna, 

Thanks for your message! It looks like bombcell is doing a good job or removing noise (those waveforms do look like artefacts). The rest of the units are all be classified as MUA, and not as good, and it looks like the fraction refractory period parameter is responsible for that. I would suggest seeing if you can tweak that (increase `param.	maxRPVviolations`) and check in the GUI that things look good for you (ie units classified as good have a ACG / ISI distribution that looks OK to you)

**Comment by jennablain** [comment]
Thank you for your fast response. Changing param. maxRPVviolations helped, but it is still giving me this:
Warning: could not plot global plots . These are the plots I get after increasing maxRPVviolations to 1 instead of 0.1. 

<img width="537" alt="Screenshot 2024-11-21 at 2 09 29 PM" src="https://github.com/user-attachments/assets/e4136f13-0eb7-43e3-a142-4025c43c731f">
<img width="1669" alt="Screenshot 2024-11-21 at 2 14 12 PM" src="https://github.com/user-attachments/assets/b4ccb89b-dcfc-4343-a67d-c4e660ab84fb">

**Comment by Julie-Fabre** [comment]
Would you mind sending me your kilosort output data (no need for the raw)? All the .npy files loaded in bc.load.loadEphyData();

**Comment by jennablain** [comment]
Two of the .npy files are over 25 MB so I am unable to send them via email or upload them to GitHub. I have been storing and accessing them via OneDrive. Do you have access to OneDrive if I shared them that way?

Jenna Blain
PhD Candidate in BME
Biomedical Engineering - UCONN
Email: ***@***.***

[cid:e2706f0d-5641-46db-a297-ff8e6c3cb1ca]
________________________________

**Comment by jennablain** [comment]
If so, this is the OneDrive link to one recording with all of the files needed.

[https://res.cdn.office.net/assets/mail/file-icon/png/folder_16x16.png]Bombcell test<https://uconn-my.sharepoint.com/:f:/g/personal/jenna_blain_uconn_edu/Ek170odnYBlBmL2buNA7thABmgoAKkrfkuQxE9Zexa4FFQ>




Jenna Blain
PhD Candidate in BME
Biomedical Engineering - UCONN
Email: ***@***.***

[cid:5678fef8-fc1b-410b-83da-3bf19a1ec95e]
________________________________

**Comment by Julie-Fabre** [comment]
Hi Jenna, 
Sorry for the delay! Thank you for sending your files. I just ran them through bombcell to take a look myself, and when running with the default bombcell setting I find a few good units (see plots below) 
![image](https://github.com/user-attachments/assets/311051b5-d07d-4502-a6d6-21c1635071ff)

![image](https://github.com/user-attachments/assets/b4eaa251-8e33-4ac6-b655-c98bcc6db863)

Could you make sure you have the default parameters and the latest version of bombcell? 

Looking through your units, you might consider lowering the refractory period window for your units or even calculating the metric for several tauR values. Bombcell will calculate the metric for values between param.tauR_valuesMin:param.tauR_valuesStep:param.tauR_valuesMax (if param.tauR_valuesMin == param.tauR_valuesMax (the default, the refractory period violations are clauclated for only one tauR value, and otherwise for several). IUn the unit below for instance, it looks like it might have a smaller tauR than 2 ms (the default). You can also look into the literature for the IC and see if the TauR values are known for cell types there. 
![image](https://github.com/user-attachments/assets/59d3f328-e3ab-4c27-bb1e-87d1352bd617)

I hope this helps!

**Comment by jennablain** [comment]
Hi Julie,

Thanks for those suggestions! I am getting some Good units ( I was able to replicate the 2nd and 3rd plots you made). For some reason the GlobalPlots is not working. I have tried different versions of MATLAb (2022b and 2024a) and I also made sure I had the most up to date version of Bombcell.

**Comment by Julie-Fabre** [comment]
That's odd. I have a try / catch statement so that bombcell doesn't error out when the output plots aren't generated. Could you remove that (l.46 and l.49-51) and tell me what bombcell errors on? 
Any MATLAB version after 2019b should work

**Comment by jennablain** [comment]
Error using histogram
Too many input arguments.

Error in bc.qm.plotGlobalQualityMetric (line 111)
                    h = histogram(ax, metricData, 'FaceColor', colorMtx(i, 1:3), 'Normalization', 'probability');




Error in bc.qm.runAllQualityMetrics (line 207)
bc.qm.plotGlobalQualityMetric(qMetric, param, unitType, uniqueTemplates, forGUI.tempWv);

Error in bombcell_batch (line 48)
[qMetric, unitType] = bc.qm.runAllQualityMetrics(param, spikeTimes_samples, spikeTemplates,templateWaveforms, templateAmplitudes, pcFeatures, pcFeatureIdx,
channelPositions, savePath);

**Comment by jennablain** [comment]
When I remove the try/catch this is the error I get.

**Comment by Julie-Fabre** [comment]
Oh interesting! histogram() is a built-in MATLAB function that has taken this input arguments for a while now. Do you have any other functions called histogram by any chance that could be creating some conflicts? (If you type "open histogram" which function pops up?)

**Comment by jennablain** [comment]
THANK YOU! That worked... turns out another repository I downloaded had a function called histogram. This seemed to solve the issue. I appreciate all your help! I may have more questions in the future.

**Comment by Julie-Fabre** [comment]
Excellent!! Glad we got to the bottom of this! 

Closing this issue for now. Please re-open it (or open another) if other issues or questions pop up!
