### ISSUE TITLE
bug in bc_waveformShape

### ISSUE THREAD

**Issue by LaurenzMuessig** [Julie-Fabre/bombcell#22]
Hi Julie,

I think I found another bug. In line 153 of _bc_waveformShape_ (_spatialDecayFit = polyfit(channelPositions_relative(sortexChanPosIdx), spatialDecayPoints_norm,1)_), the dimensions of the 2 inputs to _polyfit_ don't agree. 1 is a column the other a row vector - I am using Matlab 2019 and it crashes unless I transpose one of them. I hope that helps. 
Cheers
Laurenz

**Comment by Julie-Fabre** [comment]
Hi Laurenz, 
Thank you very much for your message! Interesting, this doesn't happen in MATLAB >= 2022a. I've just changed it so that is also works in MATLAB 2019. 
Sorry for the (very) late reply! Let me me know if there are more MATLAB 2019 quirks that I haven't taken into account. 
Cheers
Julie
