### ISSUE TITLE
Question about .npy files

### ISSUE THREAD

**Issue by nikhilchandra** [Julie-Fabre/bombcell#243]
While reading through the MATLAB code for bombcell, I notice references to spike_times_corrected.npy and spike_datasets.npy. Where do these come from? 

When I run Kilosort4 these are the .npy files I see:

- amplitudes.npy
- channel_map.npy
- channel_positions.npy
- kept_spikes.npy
- ops.npy
- similar_templates.npy
- spike_clusters.npy
- spike_detection_templates.npy
- spike_positions.npy
- spike_templates.npy
- spike_times.npy
- templates.npy
- templates_ind.npy
- whitening_mat.npy
- whitening_mat_dat.npy
- whitening_mat_inv.npy

Thank you.

**Comment by Julie-Fabre** [comment]
Hi Nikhil, 
spike_times_corrected.npy and spike_datasets.npy are generated if you run PyKilosort to stitch sessions together (like in this paper: https://www.science.org/doi/10.1126/science.abf4588)

**Comment by nikhilchandra** [comment]
I see. Follow up question -- Based on my reading of the code, the presence of these two files is not strictly necessary and therefore someone using KS3 or KS4 via SpikeInterface can still use bombcell subsequently?

**Comment by Julie-Fabre** [comment]
Yes, absolutely! You don't need these files. If you've run KS 2, KS2.5, KS3 or KS4 either directly or via spikeInterface, you can use bombcell.
