### ISSUE TITLE
Unit stability and properties during clinical events

### ISSUE THREAD

**Issue by pseudojulie** [Julie-Fabre/bombcell#252]
Question submitted by email:

I've been enjoying using bombcell. I am analyzing a neuropixel dataset during which the subject had a clinical event and trying to characterize the neuronal firing during the event. 

The sorting algorithms and quality control like bombcell usually assume stationarity in the waveform characteristics. So how can I tease out if the firing pattern/waveform changed rather than actually losing the cell. 

Happy to chat if you have time.

**Comment by Julie-Fabre** [comment]
I think you are referring to two questions: 
1. Unit tracking across the  clinical event time period. Are you losing you units (i.e. there are no spikes) during the clinical time window? 
If so:
   - You can optimize your spike-sorter. Are you using kilosort as a spike-sorter? If so, which version? Version 2 usually does a great job of tracking waveforms if there is drift / different properties (for instance bursts that result in changes in the spike shape). 
   - You can optimize your post processing. 
      - Bombcell will not (at least currently) help in recovering spikes that were lost / spikes split into other units. 
However, bombcell can be combined with [unit-match](https://github.com/EnnyvanBeest/UnitMatch) (indeed bombcell is a dependency of unitmatch). I highly recommend this software! It was designed to track cells over days chronically, but it can also help merge units within one day. 
      - You can also manually curate your dataset with [phy](https://phy.readthedocs.io/en/latest/). More resources on this [here](https://github.com/Julie-Fabre/awesome_neuropixels?tab=readme-ov-file#quality-control)
      -
2. Characterizing the changes in firing statistics over the clinical event time period. This analysis is independent of any spike-sorting of curation. 

All the best, 
Julie

**Comment by pseudojulie** [comment]
Thanks for your help! 

i am using kilosort 2.5. Do you recommend switching ? Are there any settings I should tweak?

**Comment by Julie-Fabre** [comment]
Are you visibly losing your units during the clinical time period? I.e. there are no spikes at that time for some units? If yes, I would recommend first trying out different kilosort versions - specifically kilosort2 and kilosort4. These both should handle drift better than 2.5. Regarding parameters, I would recommend asking the kilosort team. I am most familiar with Kilosort2, and in this version you could try tweaking the ops.lambda parameter (lowering it). The individual spike amplitudes are biased towards the mean of the cluster by this factor; 50 is a lot, 0 is no bias.

When you're happy and you've found whichever software version/parameter works best in your case, I would recommend using bombcell + unitmatch together to merge units or manually curating your dataset
