### ISSUE TITLE
bug in 'bc_getQualityUnitType'?

### ISSUE THREAD

**Issue by LaurenzMuessig** [Julie-Fabre/bombcell#29]
Hi Julie,

In 'bc_getQualityUnitType' you do  _qMetric.fractionRPVs_estimatedTauR <= param.maxRPVviolations_ in multiples places.  Shouldn't it be _qMetric.fractionRPVs <= param.maxRPVviolations_. At least for me 'qMetric.fractionRPVs_estimatedTauR' doesn't get computed anymore. At least I can't see it. Thanks for your help. 

Cheers

Laurenz

**Comment by LaurenzMuessig** [comment]
Okay. I think I figured out where the problem comes from. When qMetrics doesn't get converted to a table in _bc_saveQMetrics_ (if e.g. the try/catch statement in _bc_runAllQualityMetrics_ produces an error), then you end up with the original structure where the field is called _fractionRPVs_.

**Comment by Julie-Fabre** [comment]
Hi Laurenz, 
Yes, well spotted! I just pushed a commit to fix this - now bombcell checks in `bc_getQualityUnitType` if the correct fields exist, and creates them it not. 
Thanks a lot for your github issue, Laurenz!

**Comment by LaurenzMuessig** [comment]
Hi Julie,
Me again. Sorry. Your fix doesn't work (at least in my Matlab version). In _bc_getQualityUnitType_ line 10 you can't use isfield() on a table (seems to always return 0 and so will always enter inside conditional statement where it fails in case qMetrics is a table). Instead for a table you would need to do something like _~ismember('fractionRPVs_estimatedTauR', qMetric.Properties.VariableNames)_. You could just add an _isstruct_ to the if statement but I am not sure exactly in which format and with which fields/varnames qMetrics might arrive at this stage of the pipeline. Otherwise I would have just done a PR.    

Cheers

Laurenz

**Comment by Julie-Fabre** [comment]
Yes, you are right! Really sorry about that, I shamefully patched this one without testing. I added an `isstruct` for good measure in [this commit](https://github.com/Julie-Fabre/bombcell/commit/3085c876629c59e414629d52d455f4fa41fba894). Its should be fine now, but I am not able to test it until Monday. Let me know if there any issues. 

Thanks again, Laurenz!

**Comment by LaurenzMuessig** [comment]
No worries. Happy to help.
