### ISSUE TITLE
classification in somatic and non-somatic units

### ISSUE THREAD

**Issue by LaurenzMuessig** [Julie-Fabre/bombcell#42]
Hi Julie,

I think the way you characterise non-somatic units might be a bit too strict. See below an example where, imo, the way you have implemented it in your pipeline misclassifies the unit, I see fair amount of these in my data. Maybe this works better for your data but I thought I'd let you know. 

![non_somatic](https://github.com/Julie-Fabre/bombcell/assets/24457903/8f442c7d-392c-49b4-8fe1-e90b9307043e)

Cheers

Laurenz

**Comment by Julie-Fabre** [comment]
Hi Laurenz, 

Thanks a lot for your message! That unit is definitely miss-classified and it's an issue if there a lot of these in some datasets. I haven't really seen units like these before. Would you be able to send the template waveform for this one (and maybe some others - you can send the full dataset template waveforms if you want) to me so I can play around and see how to resolve this issue? 
Out of curiosity, where in the brain are you recording, with which probes and which kilosort version do you use? 

P.S. I need to fix this plot - it does not work well with landscape mode screens!

**Comment by Julie-Fabre** [comment]
I've made some tweaks. Now, if a waveform's largest detected peak is before the trough, it is no longer automatically classified as non-somatic. This peak needs to be larger than `param.firstPeakRatio` times any peaks after the trough. For now, I have set `param.firstPeakRatio` to `1.1` . Let me know if this works for you.

**Comment by Julie-Fabre** [comment]
Marking this as closed for now. Re-open the issue if it's not resolved for you. 
Cheers!
