### ISSUE TITLE
error with bc_loadMetricsForGUI

### ISSUE THREAD

**Issue by NJamann** [Julie-Fabre/bombcell#53]
Hi Julie,

First of all thanks for generating this great tool!
I am running you pipeline for the first time on my data with the example script so it might be an error on my side. The computing of the quality metrics seems to work, however when I try to start the GUI with bc_loadMetricsForGUI I get the following error:

Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.

Error in bc_removeDuplicateSpikes (line 72)
    if ~isempty(pcFeatures) || ~isnan(pcFeatures)

Error in bc_loadMetricsForGUI (line 49)
    bc_removeDuplicateSpikes(ephysData.spike_times_samples, ephysData.spike_templates, ephysData.template_amplitudes,...

Error in bc_qualityMetrics_pipeline (line 62)
bc_loadMetricsForGUI;

I hope you can figure out with this information what the problem is :)
Best,
Nora

**Comment by NJamann** [comment]
Hi Julie,

Thanks for you quick help, it works now!

I have another (hopefully) small request: In your wiki it states that there will be 3 plots after computing the quality metrics, however it did not show the Euler diagram for me, only the other two.

Best,
Nora

**Comment by Julie-Fabre** [comment]
Hi Nora, 

Thanks again for your message! I've finally implemented UpSet plots in bombcell. If you pull/clone the latest code, they should be automatically generated when you run `bc_runAllQualityMetrics`. Currently bombcell outputs 2 (or 3, if you have `param.splitGoodAndMua_NonSomatic` set to true), which show (1) quality metrics for noise vs neuronal units (2)  quality metrics for MUA vs well isolated, single somatic units (and, optionally (3) quality metrics for MUA vs well isolated, single non-somatic units).

Here are some more details on [what they are](https://upset.app/) and [the original paper that introduced them](https://sci.utah.edu/~vdl/papers/2014_infovis_upset.pdf). 

Let me know if you have any questions or run into any issues! 

Cheers, 
Julie

**Comment by NJamann** [comment]
Dear Julie,

I ran the new feature yesterday without any problems. Thank you so much for implementing it!

Cheers,
Nora

**Comment by Julie-Fabre** [comment]
Wonderful, I'm happy to hear that! Happy bombcell-ing and thanks again for the nudge!
