### ISSUE TITLE
Error in bc_waveformShape

### ISSUE THREAD

**Issue by fvalerio** [Julie-Fabre/bombcell#60]
Hi Julie, 
Thank you very much for this great tool! I love it!
I am running your pipeline on my data with the example script and I get the following error:

Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.

Error in bc_waveformShape (line 125)
if peakLoc > troughLoc && max(TRS) > max(PKS)

Error in bc_runAllQualityMetrics (line 159)
        forGUI.tempWv(iUnit, :)] = bc_waveformShape(templateWaveforms, thisUnit, qMetric.maxChannels(thisUnit), ...

Error in Pipeline_code (line 49)
    [qMetric, unitType] = bc_runAllQualityMetrics(param, spikeTimes_samples, spikeTemplates, ...

For additional info: peakLoc and troughLoc are empty variables while TRS and PKS are nan values. This happens for a specific unit only, but works fine on other units. 
I think it might be related to issue #53 but I might be wrong. It might also just be me. 

Hope it's an easy fix and thanks for your help, 
Valerio

**Comment by Julie-Fabre** [comment]
Hi Valerio, thanks a lot for your message!  It sounds like most likely no peak or no trough is detected in this waveform for some reason. Would you be able to send me the waveform for this unit so I can take a look?You can send me either full `templates.npy` file and the unit number.
Cheers
Julie

**Comment by fvalerio** [comment]
You can find it here:
https://drive.google.com/file/d/1n5cWXJink2VgVOgmDDrnzBdHboYs8Rye/view?usp=sharing
It's unit ('iUnit') 357 (Matlab indexing)
Thank you

**Comment by Julie-Fabre** [comment]
Great thank you! 
Sorry I just realized - I also need the `spike_templates.npy` file. Would you be able to send it over?

**Comment by fvalerio** [comment]
Hi Julie, don't worry and thank you for your help. 
https://drive.google.com/drive/folders/12VnfWSyFBPD6FFCn6quv-wI5B3AhaPtF?usp=sharing

**Comment by Julie-Fabre** [comment]
Wonderful, thank you! Could you also tell me which Kilosort version you re using?

I reproduced the error you got and it is due to the template waveform for unit # 357 being all NaNs. This error is probably related to [a previously signalled error](https://github.com/Julie-Fabre/bombcell/issues/28), where some versions of Kilosort (2.5) can output templateWaveforms that are all NaNs. I still don't understand why this is the case, but, considering the waveforms are NaNs, I believe these units should be skipped and automatically classified as noise by bombcell.

I had previously created [a branch](https://github.com/Julie-Fabre/bombcell/tree/waveform_nans) to deal with scenario. Since it is now reproduced and affects more than one person, I will integrate these changes in the main branch later today.

**Comment by fvalerio** [comment]
Amazing! Thank you :):)
Yes, you're right, I'm using Kilosort 2.5. 
Thank you for the link to the other issue. I'm going to further hunt it down from the kilosort side but in the meantime, I really appreciate you dealing with it. 
Super efficient. Thanks again!

**Comment by Julie-Fabre** [comment]
I've now updated bombcell to handle this situation in the main branch ([pull request #61](https://github.com/Julie-Fabre/bombcell/pull/61) ). Let me know if there are any issues. 

As a sanity check, could you tell me, when you look at this unit in phy (it should be unit #359) does any waveform show up?

**Comment by fvalerio** [comment]
Yeah, it's a weird one. 
![phyUnit](https://github.com/Julie-Fabre/bombcell/assets/15000068/e32fcbdf-f21a-4b49-ba61-8ff05dc41b77)

Thank you for updating the code! I'll try it right now

**Comment by fvalerio** [comment]
I get the following error: 
Unable to perform assignment because the left and right sides have a different number of elements.

Error in bc_computeAllEphysProperties (line 56)
    [ephysProperties.waveformDuration_peakTrough_us(iUnit), ephysProperties.halfWidth_ms(iUnit), ...

Error in bc_ephysPropertiesPipeline (line 11)
    ephysProperties = bc_computeAllEphysProperties(spikeTimes_samples, spikeTemplates, templateWaveforms,...

Error in Pipeline_code (line 111)
[ephysProperties, unitClassif] = bc_ephysPropertiesPipeline(ephysKilosortPath, savePath, rerunEP, region);

It happens on the incriminated iUnit :'(

**Comment by Julie-Fabre** [comment]
Sorry I missed this message.
Good point, I hadn't updated the ephysProperties to deal with these NaN waveforms. It should be good now! Let me know if there are any issues.

**Comment by fvalerio** [comment]
Sweet! This ran smoothly on the dataset I could not run onto before. Thank you very much. Very appreciated! I'm going to close the issue
