### ISSUE TITLE
bc_classifyCells needs `region` as third input argument

### ISSUE THREAD

**Issue by lachioma** [Julie-Fabre/bombcell#69]
Hi Julie!
I think the function [bc_classifyCells](https://github.com/Julie-Fabre/bombcell/blob/main/ephysProperties/bc_classifyCells.m) needs `region` as third input argument.
Accordingly, where the function is called, [here](https://github.com/Julie-Fabre/bombcell/blob/98016ede9371dfc4d2eb6b50d645952d3ff1ee90/ephysProperties/bc_ephysPropertiesPipeline.m#L23), would need to be changed.
Alessandro

**Comment by Julie-Fabre** [comment]
Hi Alessandro, 
Good catch! Fixed 
Thanks a lot,
Julie
