### ISSUE TITLE
max drift.tsv has NaN values 

### ISSUE THREAD

**Issue by hemant22** [Julie-Fabre/bombcell#70]
Hi, 
Bombcell outputs all NaN values for max drift. I used kilosort3 to extract units which outputs pc features as empty variable. Is there a way to get max drift with kilosort 3 output?

**Comment by Julie-Fabre** [comment]
Hi, 

Thanks you for your message! 
Bombcell needs the `pcFeatures.npy` file to compute the drift (that's how it's currently defined). Currently, if you want to compute drift estimates, you would need to switch a version that outputs this file -- either Kilosort2, 2.5 or PyKilosort (python version mainly based on Kilosort 2.5).

**Comment by hemant22** [comment]
Thanks a lot for your response.

**Comment by Julie-Fabre** [comment]
No problem :)
