### ISSUE TITLE
fontname function introduced after R2022b

### ISSUE THREAD

**Issue by abisi** [Julie-Fabre/bombcell#85]
Hi!

First, thanks for your tool!

I use R2021b to run Kilosort (for CUDA reasons...) and in that version `fontname` does not exist yet, used in `prettify_plot.m`.

If deemed useful, I could do a pull request specifying the MATLAB version used in order to use, or not, this function.

Best,
Axel

**Comment by Julie-Fabre** [comment]
Hi Axel, 

Thanks for your message and sorry for the late reply. The function fontname() is used to set matlab plot fonts to Arial in prettify_plots. There's no real need for it, so I've just added a try/catch statement for now. Let me know if you run into any other issues! And in the future feel free to submit a pull request directly if you want to- they're always welcome :)

**Comment by abisi** [comment]
Hi! Great, my modification was exactly that. Somehow I couldn't perform a PR (either on my side, or the repo is protected?). Thanks anyways!

**Comment by Julie-Fabre** [comment]
Oh weird, the repo shouldn't be protected. I'll check it out, thanks! Closing this issue for now, thanks again for the message.
