### ISSUE TITLE
Discrepancy between ContamPct and frac_RPVs

### ISSUE THREAD

**Issue by Peyton-D** [Julie-Fabre/bombcell#89]
Hello, 

Usually there is correspondence between Kilosort's ContamPct and Bombcell's frac_RPV metrics, but occasionally there will be units where the values are completely different (see cluster IDs 10, 55, 71, and 101 in the attached screenshot). As a result, I'm not sure whether these units actually meet the criteria for inclusion. Have you noticed a discrepancy before? 

![Screenshot 2024-05-29 104153](https://github.com/Julie-Fabre/bombcell/assets/148901494/d87e6cbd-2335-4ecc-a3cd-cf6f70eb740f)

**Comment by Julie-Fabre** [comment]
Hi Peyton, 

In bombcell, the estimate is based on this [Hill et al., metric](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123734/) . I had quick look at kilosort and I couldn't quickly find any documentation how they are calculating ContamPct. Depending on how it's done, that will account for quite a lot of difference.

In bombcell, it will also additionally depend on two things:
- if you're estimating drift in chunks and then selecting time chunks based on those
- if you're estimating several refractory period violations based on different `tauR` refractory period times (which is disable be default, and I don't currently recommend doing).

In your case, the bombcell estimate looks off for unit 10 -- at least if you're using the whole recording (not selecting particular times) to calculate it and if you're using the standard `tauR` value of 2s. Which values are you using for the following parameters:
- `tauR_valuesMin`
- `tauR_valuesStep`
- `tauR_valuesMax`
- `computeTimeChunks`

**Comment by Peyton-D** [comment]
Thanks for the quick response! 

Here's a quote from the Kilosort github regarding ContamPct calculation: "ContamPct is the estimated contamination, based on the number of refractory period violations. This is roughly the ratio of the event rate in the central 2ms bin of the histogram to the baseline of the auto-correlogram (the "shoulders")." Also, I should mention I'm using Kilosort 4. 

I believe I'm using the default bombcell parameters from bc_qualityParamValues:

param.tauR_valuesMin = 2/1000;
param.tauR_valuesStep = 0.5/1000;
param.tauR_valuesMax = 2/1000;
param.tauC = 0.1/1000;

param.computeTimeChunks = 1;
param.deltaTimeChunk = 360;

**Comment by Julie-Fabre** [comment]
Thanks for the information! 

Given your param values:
- bombcell is computing the fraction of refractory period violations for `tauR` (the refractory period window) of 2ms. That looks good. 
- bombcell is computing the refractory period violations (and the estimated percentage of spikes missing) in chunks of time of size 360s. Likely bombcell is selecting some times here, and this accounts for the big discrepency between kilosort and bombcell. For this unit only, could you run the loop in `bc_runAllQualityMetrics` with `param.plotDetails = 1` and then send the output plot for the refractory period violations and percentage spikes missing ? They should both look like the plots attached -- top is percentage spikes missing and bottom is refractory period violations, for each time chunk. 

![image](https://github.com/Julie-Fabre/bombcell/assets/29582008/9b05515a-49ce-4e0b-ac4f-4a25b9fd8bfd)


About Kilosort's ContamPct: thanks for the quote. That doesn't tell us much about how they actually estimate the fraction of refractory period violations - there are many different ways of doing this.

**Comment by Peyton-D** [comment]
For unit 10: 

![missingSpikes](https://github.com/Julie-Fabre/bombcell/assets/148901494/78fcbbd5-3934-488f-96d0-f39ec6dcf6b2)
![rpv](https://github.com/Julie-Fabre/bombcell/assets/148901494/aa4eb546-a629-47fa-805d-9ec79d6e5a52)

**Comment by Julie-Fabre** [comment]
Thanks! From the bottom plot, bombcell is selecting two first time chunks as good time chunks (outputed in `qMetric.useTheseTimesStart` and `qMetric.useTheseTimesStop` for each unit) to compute quality metrics, including the final refractory period violations (RPVs) estimate. Doing this is a good way of dealing with things like drift: over the course the recording, usually units drift which can result in more or less contamination at different parts of the recording. For this unit, most likely it  has spikes from two different neurons in the middle and last time chunks, but not in the first. It would be thrown out with classical methods using the whole recording, but if you select for certain times the unit can be used. 

You can play around with this, and decide you don't want to select good times for each unit. In that case, set `param.computeTimeChunks = 0` or that you want bigger time chunks - that is controlled by `param.deltaTimeChunk` (in seconds). 

Kilosort and Phy load the whole recording without selecting for any time chunks, and this accounts for the discrepancy between ContamPct and bombcell's estimate. 

P.S.: It's a little hard to see the RPV plot and check whether bombcell is actually doing a good job. I pushed a commit recently to fix this and only display 0 to 10 ms of the interspike interval in the plots. I suggest you pull that recent change or change line 81 in `bc_fractionRPviolations` from ` [isiProba, edgesISI] = histcounts(theseisiclean*1000, [0:0.5:50]);` to ` [isiProba, edgesISI] = histcounts(theseisiclean*1000, [0:0.5:10]);`

**Comment by Julie-Fabre** [comment]
Another thing - if computing time chunks, it is very important to then use `qMetric.useTheseTimesStart` and `qMetric.useTheseTimesStop` for each unit in all your subsequent analysis! I wonder if this wasn't clear enough, I might add a warning in the script so it's very clear.

**Comment by Peyton-D** [comment]
Ah I see, param.computeTimeChunks = 1 was the problem. I need to be able to use spikes from the entire recording, so param.computeTimeChunks = 0 is the way to go (and leads to better correspondence between contamPct and frac_RPV). Thanks for your help!
